# Generated by Django 2.0.4 on 2018-05-10 08:52

from django.db import migrations, models
import helpful.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='bg',
            field=models.FileField(blank=True, null=True, upload_to=helpful.fields.upload_to, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=helpful.fields.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='element',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=helpful.fields.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.FileField(blank=True, upload_to=helpful.fields.upload_to, verbose_name='Image'),
        ),
    ]
