# Generated by Django 2.0.4 on 2018-07-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20180510_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='url',
            field=models.CharField(default='#', max_length=1024, verbose_name='URL'),
        ),
    ]
