# Generated by Django 2.0.4 on 2018-07-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_block_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=1024, null=True, verbose_name='URL'),
        ),
    ]
