# Generated by Django 2.0.4 on 2018-08-23 11:11

from django.db import migrations, models
import django.db.models.deletion
import helpful.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180725_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Description')),
                ('doc', models.FileField(blank=True, null=True, upload_to=helpful.fields.upload_to, verbose_name='Document')),
                ('sorting', models.PositiveIntegerField(default=500, verbose_name='Sorting')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='cms.Page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['sorting'],
            },
        ),
    ]
